"""add_on_delete_cascade_to_items

Revision ID: 251ed6151cd5
Revises: 4a3aeaad3195
Create Date: 2026-03-23 23:18:03.530607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '251ed6151cd5'
down_revision: Union[str, Sequence[str], None] = '4a3aeaad3195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('items_wishlist_id_fkey'), 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'wishlists', ['wishlist_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key(op.f('items_wishlist_id_fkey'), 'items', 'wishlists', ['wishlist_id'], ['id'])
    # ### end Alembic commands ###
