"""add_on_delete_cascade_to_notifications

Revision ID: 4a3aeaad3195
Revises: 9e35ab0b56ea
Create Date: 2026-03-23 23:04:04.842260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a3aeaad3195'
down_revision: Union[str, Sequence[str], None] = '9e35ab0b56ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('notifications_item_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('price_history_item_id_fkey'), 'price_history', type_='foreignkey')
    op.create_foreign_key(None, 'price_history', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'price_history', type_='foreignkey')
    op.create_foreign_key(op.f('price_history_item_id_fkey'), 'price_history', 'items', ['item_id'], ['id'])
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_item_id_fkey'), 'notifications', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###
