#comma separated list of wishlists
wishlist.urls=https://www.amazon.es/hz/wishlist/ls/15GUT1Z52APS9?ref_=list_d_wl_lfu_nav_3,https://www.amazon.es/hz/wishlist/ls/1VB45OTWGKVMD?ref_=list_d_wl_lfu_nav_1

#TELEGRAM|EMAIL
notification_method=TELEGRAM

#telegram configuration
telegram.token=5400964186:AAEdTzsP5MSdl1XYCOAVO1k3AXNApGoKQjY
telegram.chatid=793366539


#email configuration
email.username=
email.password=
email.host=smtp.gmail.com
email.port=465
email.from=priceupdate@amazon.priceupdate.notification.com
email.to=
email.subject="Amazon price change notification

#Minimum savings percentage between normal price and Used price.Used to notify only when that condition meets.
notification.savings.percentage=0.10

#Keywords to identify used products. Comma-separated.
used.condition.keywords=Used,De 2ª mano,Usado
