services:
  amazon-price-notifier:
    build: .
    volumes:
      - ./amazonPriceUpdateNotifier.properties:/app/amazonPriceUpdateNotifier.properties
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
