services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wishlist
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"

  scraper:
    build: .
    volumes:
      - ./amazonPriceUpdateNotifier.properties:/app/amazonPriceUpdateNotifier.properties
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://user:password@db/wishlist
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    depends_on:
      - db
    restart: unless-stopped
    command: python amazonPriceUpdateNotification.py

  api:
    build: .
    ports:
      - "8010:8010"
    environment:
      - DATABASE_URL=postgresql://user:password@db/wishlist
    depends_on:
      - db
    restart: unless-stopped
    command: python api.py

volumes:
  postgres_data:
