#telegram configuration
telegram.token=
telegram.chatid=


#Minimum savings percentage between normal price and Used price.Used to notify only when that condition meets.
notification.savings.percentage=0.10

#Maximum historical data points to keep per item.
history.limit=100

#Keywords to identify used products. Comma-separated.
used.condition.keywords=Used,De 2ª mano,Usado
